syntax = "proto3";
package job.v1;

import "google/protobuf/timestamp.proto";

option go_package = "spool/protos";

enum JobStatus {
    JOB_STATUS_UNSPECIFIED = 0;
    JOB_STATUS_PENDING = 1;
    JOB_STATUS_COMPLETED = 2;
    JOB_STATUS_FAILED = 3;
    JOB_STATUS_RUNNING = 4;
}

message Job {
    string job_id = 1;
    google.protobuf.Timestamp requested_at = 2;
    google.protobuf.Timestamp updated_at = 3;
    JobStatus job_status = 4;

    message JobType {
        int32 job_type_id = 1;
        string name = 2;
    }

    JobType job_type = 5;
}